-- Create the table structure with exact data types and primary key
CREATE TABLE [M7Investimentos].[investimentos].dim_clientes (
    cod_xp INT PRIMARY KEY,
    nome_cliente VARCHAR(250),
    telefone_cliente VARCHAR(20),
    email_cliente VARCHAR(250),
    genero VARCHAR(1),
    profissao VARCHAR(250),
    crm_id_cliente VARCHAR(20),
    cpf_cliente VARCHAR(11),
    cnpj_cliente VARCHAR(14),
    data_nascimento DATE,
    segmento VARCHAR(250),
    suitability VARCHAR(20),
    tipo_investidor VARCHAR(50),
    flag_grupo_familiar TINYINT,
    [grupo familiar] VARCHAR(250),
    elegibilidade_cartao VARCHAR(50),
    produto_cartao VARCHAR(50), -- Renamed from produto
    status_conta_digital VARCHAR(50),
    status_cliente TINYINT,
    tipo_conta VARCHAR(2),
    segmento_pj VARCHAR(50),
    patrimonio_xp_atual DECIMAL,
    patrimonio_xp_max DECIMAL,
    patrimonio_declarado DECIMAL, -- Renamed from patrimonio
    saldo_em_conta DECIMAL,
    cod_aai_assessor VARCHAR(20),
    crm_id_assessor VARCHAR(20),
    cod_aai_primeiro_assessor_m7 VARCHAR(50),
    qtd_assessores_m7 INT,
    data_ultimo_aporte DATE,
    data_ultima_ordem DATE,
    fee_based TINYINT,
    flag_open_investment TINYINT,
    saldo_open_investment DECIMAL,
    data_cadastro DATE,
    data_cadastro_m7 DATE,
    safra_ano_mes VARCHAR(6)
);

-- Insert data into the new table
INSERT INTO [M7Investimentos].[investimentos].dim_clientes
SELECT 
    COALESCE(s.cod_xp, d.cod_xp) AS cod_xp,
    COALESCE(s.nome_cliente, d.nome_cliente) AS nome_cliente,
    COALESCE(s.telefone_cliente, d.telefone_cliente) AS telefone_cliente,
    COALESCE(s.email_cliente, d.email_cliente) AS email_cliente,
    d.genero,
    d.profissao,
    d.crm_id_cliente,
    d.cpf_cliente,
    d.cnpj_cliente,
    d.data_nascimento,
    d.segmento,
    d.suitability,
    d.tipo_investidor,
    d.flag_grupo_familiar,
    d.[grupo familiar],
    COALESCE(s.elegibilidade_cartao, d.elegibilidade_cartao) AS elegibilidade_cartao,
    s.produto AS produto_cartao, -- Renamed
    COALESCE(s.status_conta_digital, d.status_conta_digital) AS status_conta_digital,
    d.status_cliente,
    d.tipo_conta,
    d.segmento_pj,
    d.patrimonio_xp_atual,
    d.patrimonio_xp_max,
    COALESCE(s.patrimonio, d.patrimonio_declarado) AS patrimonio_declarado,
    d.saldo_em_conta,
    d.cod_aai_assessor,
    d.crm_id_assessor,
    d.cod_aai_primeiro_assessor_m7,
    d.qtd_assessores_m7,
    d.data_ultimo_aporte,
    d.data_ultima_ordem,
    d.fee_based,
    d.flag_open_investment,
    d.saldo_open_investment,
    d.data_cadastro,
    d.data_cadastro_m7,
    d.safra_ano_mes
FROM [M7InvestimentosOLAP].[DS].[dim_clientes] d
FULL OUTER JOIN [M7InvestimentosOLAP].[DS].[stage_clientes_rpa] s
    ON d.cod_xp = s.cod_xp;