SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [bronze].[xp_nps_respostas](
	[survey_id] [varchar](50) NULL,
	[id_usuario] [varchar](50) NULL,
	[customer_id] [varchar](50) NULL,
	[cod_assessor] [varchar](20) NULL,
	[codigo_escritorio] [varchar](20) NULL,
	[data_resposta] [date] NULL,
	[delivered_on_date] [date] NULL,
	[data_cadastro] [date] NULL,
	[faixa_net] [varchar](50) NULL,
	[faixa_pld] [varchar](50) NULL,
	[area] [varchar](100) NULL,
	[canal] [varchar](50) NULL,
	[suitability] [varchar](50) NULL,
	[area_transacional] [varchar](100) NULL,
	[xp_assessores_survey_type] [varchar](100) NULL,
	[pesquisa_relacionamento] [varchar](100) NULL,
	[xp_aniversario_nps_assessor] [float] NULL,
	[xp_onboarding_nps] [float] NULL,
	[clear_onboarding_nps] [float] NULL,
	[rico_onboarding_nps] [float] NULL,
	[xp_aniversario_nps_xp] [float] NULL,
	[clear_aniversario_nps] [float] NULL,
	[rico_aniversario_nps] [float] NULL,
	[transacional_satisfacao_assessor] [float] NULL,
	[transacional_comentario_satisfacao] [nvarchar](max) NULL,
	[xp_onboarding_comentario] [nvarchar](max) NULL,
	[clear_onboarding_comentario] [nvarchar](max) NULL,
	[rico_onboarding_comentario] [nvarchar](max) NULL,
	[xp_aniversario_comentario_assessor] [nvarchar](max) NULL,
	[xp_aniversario_comentario_xp] [nvarchar](max) NULL,
	[clear_aniversario_comentario] [nvarchar](max) NULL,
	[rico_aniversario_comentario] [nvarchar](max) NULL,
	[open_comment] [nvarchar](max) NULL,
	[clear_razao_nps] [varchar](255) NULL,
	[rico_razao_nps] [varchar](255) NULL,
	[xp_razao_nps] [varchar](255) NULL,
	[clear_aniversario_razao_nps] [varchar](255) NULL,
	[clear_onboarding_razao_nps] [varchar](255) NULL,
	[rico_aniversario_razao_nps] [varchar](255) NULL,
	[rico_onboarding_razao_nps] [varchar](255) NULL,
	[xp_aniversario_razao_nps_assessor] [varchar](255) NULL,
	[xp_aniversario_razao_nps_xp] [varchar](255) NULL,
	[xp_onboarding_razao_nps] [varchar](255) NULL,
	[xp_aniversario_email_amigo_familiar] [varchar](255) NULL,
	[xp_aniversario_recomendaria_assessor] [varchar](50) NULL,
	[link_to_response] [varchar](500) NULL,
	[link_to_response_2] [varchar](500) NULL,
	[pld] [varchar](50) NULL,
	[genero] [varchar](20) NULL,
	[usuarios_ativos] [varchar](50) NULL,
	[cliente_max] [varchar](50) NULL,
	[cliente_max_simulacao] [varchar](50) NULL,
	[persona] [varchar](100) NULL,
	[faixa_atendimento] [varchar](100) NULL,
	[grupo_atendimento] [varchar](100) NULL,
	[topics_tagged_original] [varchar](500) NULL,
	[unit_secundaria_digital] [varchar](100) NULL,
	[first_name] [varchar](100) NULL,
	[email] [varchar](255) NULL,
	[previdencia_atual] [varchar](100) NULL,
	[receber_comparativo_proposta] [varchar](50) NULL,
	[valor_previdencia] [decimal](18, 2) NULL,
	[voce_gostaria_responder_duas_questoes] [varchar](10) NULL,
	[global_relacionamento_subatributo] [varchar](255) NULL,
	[rico_relacionamento_subatributo] [varchar](255) NULL,
	[data_carga] [date] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [bronze].[xp_nps_respostas] ADD  DEFAULT (CONVERT([date],getdate())) FOR [data_carga]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Tabela com dados de respostas de pesquisas NPS (Net Promoter Score) extraídos do Hub XP. Contém múltiplas variações de notas NPS para diferentes canais (XP, Clear, Rico) e momentos (onboarding, aniversário)' , @level0type=N'SCHEMA',@level0name=N'bronze', @level1type=N'TABLE',@level1name=N'xp_nps_respostas'
GO
